# Generated by Django 4.1.3 on 2022-12-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_all_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following_Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=500)),
                ('following', models.IntegerField()),
                ('followers', models.IntegerField()),
            ],
        ),
    ]
