# Generated by Django 4.1.3 on 2022-12-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_following_followers_followers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Following_Followers',
            new_name='Following_Follower',
        ),
    ]
