# Generated by Django 4.1.3 on 2022-12-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_following_followers_following_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='following_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.TextField(max_length=500)),
                ('leader', models.TextField(max_length=500)),
            ],
        ),
    ]
