# Generated by Django 4.1.3 on 2022-12-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_following_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_post',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
