# Generated by Django 4.1.3 on 2022-12-11 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_all_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_post',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
