# Generated by Django 4.1.3 on 2022-12-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_all_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='liked_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.TextField(max_length=500)),
                ('receiver', models.TextField(max_length=500)),
            ],
        ),
    ]
