# Generated by Django 4.1.3 on 2022-12-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_liked_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked_system',
            old_name='receiver',
            new_name='receiverId',
        ),
    ]
