# Generated by Django 4.1.3 on 2022-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_rename_receiver_liked_system_receiverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked_system',
            name='receiverId',
            field=models.IntegerField(max_length=500),
        ),
    ]
